local history = require("ledger.builder.history")

describe("ledger.builder.history", function()
  before_each(function()
    history._reset()
  end)

  it("records and returns recent entries newest-last", function()
    history.record({ label = "a", kind = "build", code = 0, duration = 10 })
    history.record({ label = "b", kind = "build", code = 1, duration = 20 })
    local r = history.recent(8)
    assert.equals(2, #r)
    assert.equals("a", r[1].label)
    assert.equals("b", r[2].label)
  end)

  it("filters recent by kind", function()
    history.record({ label = "build1", kind = "build", code = 0, duration = 5 })
    history.record({ label = "test1", kind = "test", code = 0, duration = 7 })
    assert.equals(1, #history.recent(8, "build"))
    assert.equals(1, #history.recent(8, "test"))
  end)

  it("computes pass rate over test runs", function()
    history.record({ label = "t1", kind = "test", code = 0, duration = 1 })
    history.record({ label = "t2", kind = "test", code = 1, duration = 1 })
    history.record({ label = "t3", kind = "test", code = 0, duration = 1 })
    history.record({ label = "t4", kind = "test", code = 0, duration = 1 })
    local rate, n = history.pass_rate(50)
    assert.equals(75, rate)
    assert.equals(4, n)
  end)

  it("returns nil pass rate when no test runs", function()
    history.record({ label = "b", kind = "build", code = 0, duration = 1 })
    assert.is_nil(history.pass_rate(50))
  end)

  it("filters by platform (per-target stats)", function()
    history.record({ label = "d", kind = "test", code = 0, duration = 1, platform = "desktop" })
    history.record({ label = "i1", kind = "test", code = 0, duration = 1, platform = "ios" })
    history.record({ label = "i2", kind = "test", code = 1, duration = 1, platform = "ios" })
    history.record({ label = "a", kind = "build", code = 0, duration = 9, platform = "android" })
    assert.equals(1, #history.recent(8, "test", "desktop"))
    assert.equals(2, #history.recent(8, "test", "ios"))
    assert.equals(50, history.pass_rate(50, "ios"))
    assert.equals(100, history.pass_rate(50, "desktop"))
    assert.same({ 9 }, history.build_durations(8, "android"))
  end)

  it("returns build durations oldest->newest", function()
    history.record({ label = "b1", kind = "build", code = 0, duration = 11 })
    history.record({ label = "b2", kind = "build", code = 0, duration = 22 })
    local d = history.build_durations(12)
    assert.same({ 11, 22 }, d)
  end)

  it("persists across a cache reload", function()
    history.record({ label = "persisted", kind = "build", code = 0, duration = 3 })
    history._entries = nil -- force reload from disk
    local r = history.recent(8)
    assert.equals("persisted", r[#r].label)
  end)
end)
